name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:

  checks:
    runs-on: Ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check
        run: cargo check --profile min

      - name: Clippy
        run: cargo clippy --profile min --all-targets --all-features


  build:
    runs-on: ubuntu-latest
    needs: ["checks"]

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker.
        run: docker build .